### ISSUE TITLE
A new loading model - python dictionary input

### ISSUE THREAD

**Issue by sanjaynagi** [hringbauer/ancIBD#17]
Greetings Harald, Yilei and ancIBD devs, 

I'm Sanjay C Nagi, a postdoc working on the Anopheles 1000 genomes project and its successors. I am using ancIBD on whole, genome sequence data from mosquitoes - I had been working on my own heuristic method using opposite homozygotes to detect IBD1, however, I liked the look of the HMM in ancIBD. We work with our genomic data in the cloud, accessible via a Python package, [malariagen_data](https://github.com/malariagen/malariagen-data-python). The package allows one to load and perform complex analyses with single lines of code, and by using python-based IBD method, we can compute IBD segments 'on the fly'. 

I wanted to use ancIBD, but needed it to take input directly as numpy arrays, rather than converting a VCF to HDF5 and so on. This was pretty simple in the end, it just required a new loading model, which takes a Python dictionary as input, rather than a path to a HDF5 file. The good thing is that this doesn't modify any of the rest of the code. Would you have any interest in me adding this functionality to ancIBD itself? that way, malariagen_data could depend directly on ancIBD, rather than a fork of ancIBD. Here is the [PR adding the feature](https://github.com/sanjaynagi/ancIBD/pull/1), and here is an example of a [notebook using ancIBD with dict input](https://github.com/sanjaynagi/ag3-relatedness/blob/main/workflow/notebooks/ancIBD-run.ipynb ). If you approve, I can make a pull request from my fork of ancIBD.

Also, if you have some test data for ancIBD, Id be happy to add some testing/CI to the git repo at the same time, so that when you make changes to the package in future, you can ensure that ancIBD is still working as intended.

**Comment by hringbauer** [comment]
Hi Sanjay,

That is very cool work. Thank you for sharing it with us!

Your new loading module, "_dict_" (using your new' LoadDict` object as an additional loading model), is a neat addition to `ancIBD.` I like the way your code substituted an hdf5 file with a dictionary, allowing users to shortcut the h5 file within Python!

As you say, it does not interact with anything else - so it is a straightforward addition! I will approve your PR shortly and release an updated version of _ancIBD_ on PyPi (currently on paternity leave for my newborn daughter - so it might take a few days :)).

A test case would be super useful - as I always run the tests [here](https://github.com/hringbauer/ancIBD/blob/master/notebook/tests/unit_tests.ipynb) to check basic ancIBD functions and plots before releasing a new version.

To add a test for your module, could you share a minimal pickled test dictionary (such as a pair of samples with long IBD) and a notebook running the test data with your module (plus the expected output, such as max. IBD length)? 

All the best,
Harald

**Comment by hringbauer** [comment]
Hi @sanjaynagi , the update introducing your "dict" loading module is now live on PyPi in ancIBD v0.7.

You can also check out my test of your module in section G [of the test notebook](https://github.com/hringbauer/ancIBD/blob/master/notebook/tests/unit_tests.ipynb).

I also added the code to visualize IBD (and opposing homozygotes) from dictionary input. This is often hugely helpful for manually checking your IBD calling and playing around with parameters! See G2 of the test notebook for an example.

Thank you very much again for adding this very useful module!

**Comment by sanjaynagi** [comment]
Thanks Harald, thats awesome! my pleasure. 

Ill test out the code for visualising IBD/opposing homozygotes, looks useful! :)
