### ISSUE TITLE
issue“ancIBD”: Can this software be used to identify the kinship of non-human primates

### ISSUE THREAD

**Issue by xiaolingLIANG** [hringbauer/ancIBD#20]
Can this software be used to identify the kinship of non-human primates?

**Comment by hringbauer** [comment]
Yes, in principle, ancIBD also works for non-human primates. For example, our recent preprint [here](https://doi.org/10.1101/2024.01.09.574911) describes its successful use to detect IBD segments in imputed 4-6x sequencing depth Rhesus macaque data.

However, one needs pretty good genomic resources (e.g., a reference panel for imputing low coverage data and, ideally, a genomic map).
